### ISSUE TITLE
error message about the fiona package import

### ISSUE THREAD

**Issue by jhuntington** [WSWUP/gridwxcomp#9] opened 2019-12-02 03:23 UTC
I followed the directions on the github for the gridwxcomp and got the environment and installation setup, but unfortunately we get this error message about the fiona package import that gridwxcomp is using. I'm pretty sure fiona handles some of the GIS stuff so perhaps take a look at it.

![image](https://user-images.githubusercontent.com/11635416/69928220-df63b380-146f-11ea-9af9-cb189b6c92f0.png)

please copy your response to zleady@usbr.gov and mtansey@usbr.gov

**Comment by hwilkie-usgs** [comment] 2020-01-03 21:55
I believe this happened to me when I was working in the ProgramData directory. I postulate that it was caused by my lack of write privileges. It is probably clear that I am new to this, and perhaps your problem is unrelated and hopefully by now solved.

**Comment by JohnVolk** [comment] 2020-01-04 00:47
I believe this issue was corrected by the latest update to the environment.yml file which removed the "defaults" channel. 

Similar issues may also be resolved by setting strict channel priority for conda-forge in your .condarc file, in other words the following should be in your .condarc

`channels:`
`  - conda-forge`
`channel_priority: strict`

Similar issues have been related to the gdal version being too high, you may need gdal 2.2 or lower. From my understanding incompatibilities occurs between GIS libraries Fiona, GDAL, and Shapely, some of which the developers released versions for Unix/Linux more frequently than Windows. These issue threads may be of help in this case: 

https://github.com/Toblerity/Fiona/issues/402
https://github.com/conda-forge/fiona-feedstock/issues/89
https://github.com/conda-forge/gdal-feedstock/issues/219#issuecomment-410577468


If you are having a specific problem please create a new issue as this one was resolved through personal communication. Good luck!

**Closed as completed by JohnVolk** 2020-01-04 00:47 UTC
